apiVersion: logging.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: instance
  namespace: openshift-logging
spec:
  outputs:
  - name: loki-app
    type: loki
    loki:
      tenantKey: log_type
    url: http://lokistack-dev-gateway-http.openshift-logging.svc:8080/api/logs/v1/application/
  - name: loki-infra
    type: loki
    loki:
      tenantKey: log_type
    url: http://lokistack-dev-gateway-http.openshift-logging.svc:8080/api/logs/v1/infrastructure/
  - name: loki-audit
    type: loki
    loki:
      tenantKey: log_type
    url: http://lokistack-dev-gateway-http.openshift-logging.svc:8080/api/logs/v1/audit/
  pipelines:
  - name: send-app-logs
    inputRefs:
    - application
    outputRefs:
    - loki-app
    - default
  - name: send-infra-logs
    inputRefs:
    - infrastructure
    outputRefs:
    - loki-infra
    - default
  - name: send-audit-logs
    inputRefs:
    - audit
    outputRefs:
    - loki-audit
    - default 